import _cavernImageURL from "./ImageSources/cavernImageURL.png";
import _lavaImageURL from "./ImageSources/lavaImageURL.png";
import _cartImageURL from "./ImageSources/cartImageURL.png";
import _coinEdgeURL from "./ImageSources/coinEdgeURL.png";
import _coinImageURL from "./ImageSources/coinImageURL.png";
import tileImageURLs_0 from "./ImageSources/tileImageURLs_0.png";
import tileImageURLs_1 from "./ImageSources/tileImageURLs_1.png";
import tileImageURLs_2 from "./ImageSources/tileImageURLs_2.png";
import tileImageURLs_3 from "./ImageSources/tileImageURLs_3.png";
import tileImageURLs_4 from "./ImageSources/tileImageURLs_4.png";
import tileImageURLs_5 from "./ImageSources/tileImageURLs_5.png";
import tileImageURLs_6 from "./ImageSources/tileImageURLs_6.png";
import tileImageURLs_7 from "./ImageSources/tileImageURLs_7.png";
import tileImageURLs_8 from "./ImageSources/tileImageURLs_8.png";
import tileImageURLs_9 from "./ImageSources/tileImageURLs_9.png";
import tileImageURLs_10 from "./ImageSources/tileImageURLs_10.png";

export const cavernImageURL = _cavernImageURL;
export const lavaImageURL = _lavaImageURL;
export const cartImageURL = _cartImageURL;
export const coinEdgeURL = _coinEdgeURL;
export const coinImageURL = _coinImageURL;
export const tileImageURLs = [tileImageURLs_0, tileImageURLs_1, tileImageURLs_2, tileImageURLs_3, tileImageURLs_4, tileImageURLs_5, tileImageURLs_6, tileImageURLs_7, tileImageURLs_8, tileImageURLs_9, tileImageURLs_10];